before_script:
  - export HOME=/home/gitlab-runner
  - export LC_ALL=en_US.UTF-8
  - ''
  - export MYSQL_USERNAME=root
  - export MYSQL_PASSWORD=$MYSQL_PASS
  - export PG_USERNAME=postgres
  - export PG_PASSWROD=""
  - ''
  - ruby -v

Test:
  script:
  - spec/prepare_redmine.sh
  - bundle install --without xapian rmagick
  - bundle exec rake db:migrate
  - bundle exec rspec
