require:
  - rubocop-rails

Rails:
  Enabled: true
AllCops:
  TargetRubyVersion: 2.5

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines_special
Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines_except_namespace
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Lint/HandleExceptions:
  AllowComments: true

Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys
Style/MutableConstant:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
  EnforcedStyleForMultiline: consistent_comma
Style/SymbolArray:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
