begin
  require 'bundler/setup'
rescue LoadError
  puts 'You must `gem install bundler` and `bundle install` to run rake tasks'
end

require 'rdoc/task'

APP_RAKEFILE = File.expand_path("../spec/dummy/Rakefile", __FILE__)
load 'rails/tasks/engine.rake'

<% if engine? -%>
load 'rails/tasks/statistics.rake'
<% end %>

<% unless options[:skip_gemspec] -%>
Bundler::GemHelper.install_tasks
<% end %>
